// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as React       from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("Arrow");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "things"
                }, React.createElement("div", {
                      className: "content"
                    }, React.createElement("div", {
                          className: "arrow"
                        }, React.createElement("div", {
                              className: "curve"
                            }), React.createElement("div", {
                              className: "point"
                            }))));
    });
  return newrecord;
}

export {
  component ,
  make      ,
  
}
/* component Not a pure module */
