// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Button      from "./Button";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

function make(handleButtonClick, label, children) {
  return ReasonReact.wrapJsForReason(Button.default, {
              label: label,
              handleButtonClick: handleButtonClick
            }, children);
}

export {
  make ,
  
}
/* ./Button Not a pure module */
