// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Json_decode from "bs-json/src/Json_decode.js";

function decodeResponseJson(json) {
  return /* record */[
          /* question */Json_decode.field("question", Json_decode.string, json),
          /* answer */Json_decode.field("answer", Json_decode.string, json),
          /* responseType */Json_decode.field("type", Json_decode.string, json)
        ];
}

function parseResponseJson(json) {
  return Json_decode.field("magic", decodeResponseJson, json);
}

function fetchAnswer(url) {
  return fetch(url).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(Json_decode.field("magic", decodeResponseJson, json));
              }));
}

export {
  decodeResponseJson ,
  parseResponseJson  ,
  fetchAnswer        ,
  
}
/* No side effect */
