// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var questions = /* :: */[
  "Am I ever gonna give you up?",
  /* :: */[
    "Am I ever gonna let you down?",
    /* :: */[
      "Will I ever run around and desert you?",
      /* :: */[
        "Am I ever gonna make you cry?",
        /* :: */[
          "Am I ever gonna say goodbye?",
          /* :: */[
            "Will I ever tell a lie and hurt you?",
            /* [] */0
          ]
        ]
      ]
    ]
  ]
];

export {
  questions ,
  
}
/* No side effect */
