// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Pervasives  from "bs-platform/lib/es6/pervasives.js";
import * as Caml_format from "bs-platform/lib/es6/caml_format.js";

var baseURL = "https://8ball.delegator.com/magic/JSON/";

function makeURL(params) {
  return baseURL + encodeURIComponent(params);
}

function truncateString(num) {
  return Pervasives.string_of_float((Caml_format.caml_float_of_string(num) * 100.0 | 0) / 100.0);
}

function ensureTwoDecimalPlaces(num) {
  var result = truncateString(num);
  var length = result.length;
  if (length !== 5) {
    return truncateString(num);
  } else {
    return truncateString(num) + "0";
  }
}

export {
  baseURL                ,
  makeURL                ,
  truncateString         ,
  ensureTwoDecimalPlaces ,
  
}
/* No side effect */
